[package]
name = "cl-lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
regex="1"
strum = "0.24"
strum_macros = "0.24"
tracing = "0.1.37"
tracing-subscriber = {version = "0.3.17", features=["env-filter"]}
anyhow = "1"
